export const tabQuizJs = [
    {numero:"1", question:"Le mot clé 'var' permet de déclarer des variables",proposition:[{libele:"n'existe pas en JavaScript" , nature:false}, {libele:"locales uniquement" , nature:false}, {libele:"locales ou globales" , nature:true},{libele:"globale uniquement" , nature:false}]},
    {numero:"2", question:"Comment sortir d'une boucle for() ou while() ?", proposition:[{libele:"break" , nature:true}, {libele:"exit" , nature:false}, {libele:"continue" , nature:false},{libele:"end" , nature:false}]},
    {numero:"3", question:"Que fait i++ ?", proposition:[{libele:"renvoie la chiane 'i++'", nature:false}, {libele:"incrémente i de 1", nature:true}, {libele:"n'existe pas en JavaScript", nature:false},{libele:"declare la variable i binaire", nature:false}]},
    {numero:"4", question:"Que fait T1.push(3) sur le tableau T1 ?", proposition:[{libele:"retire les 3 derniers éléments", nature:false}, {libele:"décale tous les indices de 3 proposition", nature:false}, {libele:"ajoute l'élément 3", nature:true},{libele:"retire l'élément en 3ème proposition", nature:false}]},
    {numero:"5", question:"Une variable locale déclarée dans une fonction peut etre utilisée", proposition:[{libele:"dans cette fonction uniquement", nature:true}, {libele:"dans cette fonction et dans le script appelant", nature:false}, {libele:"dans cette fonction mais pas dans le script appel", nature:false}, {libele:"dans toutes fonctions du document HTML", nature:false}]},
    {numero:"6", question:"Comment mettre un commentaire sur plusieurs lignes ?", proposition:[{libele:"\\\\ \\\\", nature:false}, {libele:"/* */", nature:true}, {libele:"<!-->", nature:false},{libele:"// //", nature:false}]},
    {numero:"7", question:"Quel langage se prète le mieux à l'éxécution d'une requete MySQL ?", proposition:[{libele:"CSS", nature:false}, {libele:"HTML", nature:false}, {libele:"PHP", nature:true},{libele:"JavaScript", nature:false}]},
    {numero:"8", question:"Quelle est la syntaxe correcte ?", proposition:[{libele:`getElementById(window.["MonId"]);`, nature:false}, {libele:`getElementById(document.["MonId"]);`, nature:false}, {libele:`document.getElementById("MonId");`, nature:true},{libele:`window.getElementById("MonId");`, nature:false}]},
    {numero:"9", question:"window.confirm() affiche une boite de dialogue avec", proposition:[{libele:"n'existe pas en JavaScript", nature:false}, {libele:"un message et les boutons OK Annuler", nature:true}, {libele:"un message, un champ de saisie et les boutons OK Annuler", nature:false},{libele:"un message OK seul", nature:false}]},
    {numero:"10", question:`Comment se rendre à l'url : "http://www.qcmquizz.com`, proposition:[{libele:"location()", nature:false}, {libele:"window.location.href", nature:false}, {libele:"url()", nature:false},{libele:"window.location.url", nature:false}]},
    {numero:"11", question:"Quel est l'évènement inverse de onFocus ?", proposition:[{libele:"onBlur", nature:true}, {libele:"onDeselect", nature:false}, {libele:"onFocusDown", nature:false},{libele:"onFocusOff", nature:false}]},
    {numero:"12", question:`Comment placer 'test' dans le champ d'ID "chp1" sur form1 ?`, proposition:[{libele:`document.form1.chp1.text="test"`, nature:false}, {libele:`document.form1.chp1.value="test"`, nature:false}, {libele:`window.form1.chp1.text="test"`, nature:false},{libele:`window.form1.chp1.value="test"`, nature:false}]},
    {numero:"13", question:"Quelle fonction permet de temporiser l'exécution d'une commande ?", proposition:[{libele:"setTimeout()", nature:true}, {libele:"wait()", nature:false}, {libele:"SetTimer()", nature:false},{libele:"sleep()", nature:false}]},
    {numero:"14", question:"Quelle instruction ouvre une nouvele fenetre ?", proposition:[{libele:"open.url()", nature:false}, {libele:"open.html()", nature:false}, {libele:"window.open()", nature:true},{libele:"url.open()", nature:false}]},
    {numero:"15", question:"Le DOM", proposition:[{libele:"décrit la structure du document HTML ou XML", nature:true}, {libele:"est spécifique a JavaScript", nature:false}, {libele:"est un moteur de base de données", nature:false},{libele:"ne peut pas etre manipuler par JavaScript", nature:false}]},
    {numero:"16", question:"Quel évènement correspond au double click ?", proposition:[{libele:"Cet évènement n'existe pas", nature:false}, {libele:"onDclick", nature:false}, {libele:"onDblclick", nature:true},{libele:"onDoubleClick", nature:false}]},
    {numero:"17", question:`Dans la hiérachie des objets, quel est le parent direct de l'objet "checkbox" ?`, proposition:[{libele:"body", nature:false}, {libele:"onDeselect", nature:false}, {libele:"onFocusDown", nature:false},{libele:"onFocusOff", nature:false}]},
    {numero:"18", question:`L'évènement "onMouseUp" se produit quand l'utilisateur ?`, proposition:[{libele:"clique sur un objet", nature:false}, {libele:"clique en déplaçant la souris sur l'objet", nature:false}, {libele:"relache le bouton de la souris", nature:true}]},
    {numero:"19", question:"JavaScript", proposition:[{libele:"est un langage dérivé de l'ADA", nature:false}, {libele:"s'exécute sur le serveur uniquement", nature:false}, {libele:"doit etre compilé", nature:false},{libele:"s'exécute sur le client", nature:true}]}
    
]
